name: CI (Coq, Windows)

# Note that we must split up each command into a separate step for Windows, because otherwise we don't get error code
# See also https://github.com/avsm/setup-ocaml/issues/72

on:
  push:
    # branches:
      # - master
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    env:
      NJOBS: "2"
      COQ_VERSION: "8.18.0"
      COQEXTRAFLAGS: "-async-proofs-j 1"
      COQCHKEXTRAFLAGS: ""
      OPAMYES: "true"
      OPAMCONFIRMLEVEL: "unsafe-yes"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 4.14.2
    - run: opam install 'ocamlfind>=1.8.7'
    - run: opam install conf-time conf-gcc
    - run: opam pin add --kind=version coq ${{ env.COQ_VERSION }}

    - name: Work around https://github.com/actions/checkout/issues/766
      run: opam exec -- bash -l -c 'git config --global --add safe.directory "*"'

    - name: echo build params
      run: |
        ECHO ::group::wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status
        wmic cpu get caption, deviceid, name, numberofcores, maxclockspeed, status
        ECHO ::endgroup::
        ECHO ::group::wmic cpu list /format:list
        wmic cpu list /format:list
        ECHO ::endgroup::
        ECHO ::group::git config -l
        %CYGWIN_ROOT%\bin\bash.exe -l -c 'git config -l'
        ECHO ::endgroup::
        ECHO ::group::git config --global -l
        %CYGWIN_ROOT%\bin\bash.exe -l -c 'git config --global -l'
        ECHO ::endgroup::
        ECHO ::group::opam list
        opam list
        ECHO ::endgroup::
        ECHO ::group::ocamlc -config
        opam exec -- ocamlc -config
        ECHO ::endgroup::
        ECHO ::group::coqc --config
        opam exec -- coqc --config
        ECHO ::endgroup::
        ECHO ::group::coqc --version
        opam exec -- coqc --version
        ECHO ::endgroup::
        ECHO ::group::coqtop version
        echo | opam exec -- coqtop
        ECHO ::endgroup::
        ECHO ::group::make printenv
        %CYGWIN_ROOT%\bin\bash.exe -l -c 'cd "%cd%"; opam exec -- make printenv'
        ECHO ::endgroup::
        ECHO ::group::PATH
        %CYGWIN_ROOT%\bin\bash.exe -l -c 'cd "%cd%"; echo "${PATH}"'
        ECHO ::endgroup::
      shell: cmd
    - name: make
      run: opam exec -- make TIMED=1 -j${NJOBS}
